Updated to cctools 2448 to get fix for /proc/<pid>/exe for root.

diff --git a/cctools/configure b/cctools/configure
--- a/cctools/configure
+++ b/cctools/configure
@@ -2,16 +2,47 @@
 
 uname -a
 
+if [ -z "$USER" ]; then
+  USER=`whoami`
+  export USER
+fi
+
 . ./configure.tools
 
 save_arguments $0 $@
 
 major=3
-minor=5
+minor=7
 micro=0
-release_date="06/04/2012"
 
-build_user=`whoami`
+# On a release, type would be changed from TRUNK to RELEASE.  TRUNK is a useful
+# signal that the user is not using a blessed (tagged) release.
+type="TRUNK"
+
+version="$major.$minor.$micro $type"
+
+# The release date is set automatically at configure time (the default).
+# For a tagged release, this should be the hard-coded date of the release.
+release_date=`date +%m/%d/%Y`
+
+# Bourne shell is tricky when you use backtick command substitution backslash
+# has special meaning even when surrounded by single-quotes. It is necessary to
+# escape the backslash.
+# Here's what we want to exec literally:
+#   echo "$*" | sed s/#/\\#/ | sed s/\$/$$/
+# The above sed commands are to escape the output for the Makefile.
+# Arguments to configure which can be printed for version/debug information.
+configure_arguments=`echo "$*" | sed 's/#/\\\\#/' | sed 's/\\$/$$/'`
+
+# Bourne shell is tricky when you use backtick command substitution backslash
+# has special meaning even when surrounded by single-quotes. It is necessary to
+# escape the backslash.
+# Here's what we want to exec literally:
+#   uname -a | sed s/#/\\#/ | sed s/\$/$$/
+# The above sed commands are to escape the output for the Makefile.
+system_information=`uname -a | sed 's/#/\\\\#/' | sed 's/\\$/$$/'`
+
+build_user="$USER"
 build_host=`uname -n`
 build_sys=`uname -s | tr \[a-z\] \[A-Z\] | awk -F_ '{print $1}'`
 build_cpu=`uname -m | tr \[a-z\] \[A-Z\]`
@@ -41,6 +72,7 @@ include_package_makeflow="makeflow"
 include_package_ftplite="ftp_lite"
 include_package_s3tools="s3tools"
 include_package_chirp="chirp"
+include_package_doc="doc"
 
 work_queue_bindings=""
 
@@ -64,7 +96,6 @@ krb5_path="/usr"
 readline_path="/usr"
 globus_path="/usr"
 fuse_path="/usr"
-egee_path="/opt"
 rfio_path="/usr"
 dcap_path="/usr"
 irods_path="/usr"
@@ -79,7 +110,6 @@ swig_path="/usr"
 
 xrootd_arch=auto
 globus_flavor=auto
-has_egee=no
 
 ccompiler=gcc
 cxxcompiler=g++
@@ -101,7 +131,6 @@ config_python_path=auto
 config_zlib_path=yes
 
 config_krb5_path=no
-config_egee_path=no
 config_rfio_path=no
 config_dcap_path=no
 config_irods_path=no
@@ -151,11 +180,6 @@ do
 			shift
 			fuse_path=$1
 			config_fuse_path=yes
-			;;
-		--with-egee-path)
-			shift
-			egee_path=$1
-			config_egee_path=yes
 			;;
 		--with-rfio-path)
 			shift
@@ -241,6 +265,9 @@ do
 		--without-system-parrot)
 			include_package_parrot=""
 			;;
+		--without-system-doc)
+			include_package_doc=""
+			;;
 		--xrootd-arch)
 			shift
 			xrootd_arch=$1
@@ -263,7 +290,6 @@ Where options are:
 
 Where PACKAGE may be:
     readline
-    egee
     krb5
     fuse
     rfio
@@ -287,6 +313,7 @@ And SYSTEM may be:
     s3tools
     chirp
     parrot
+    doc
 EOF
 			exit 1
 			;;
@@ -301,7 +328,7 @@ done
 IFS=" "
 export IFS
 
-potential_packages="dttools ${include_package_sand} ${include_package_allpairs} ${include_package_wavefront} ${include_package_makeflow} ${include_package_ftplite} ${include_package_s3tools} ${include_package_chirp} ${include_package_parrot} doc apps"
+potential_packages="dttools ${include_package_sand} ${include_package_allpairs} ${include_package_wavefront} ${include_package_makeflow} ${include_package_ftplite} ${include_package_s3tools} ${include_package_chirp} ${include_package_parrot} ${include_package_doc}"
 
 check_multiarch
 
@@ -358,41 +385,17 @@ fi
 library_search_mode=prefer_static
 ##########################################################################
 
-if [ $config_egee_path != no ] && check_file "${egee_path}/lcg/include/lcg_util.h"
+if [ $config_rfio_path != no ] && library_search shift ${rfio_path}
 then
-	has_egee=yes
-	globus_flavor=gcc32dbgpthr
-	fix_globus_install ${egee_path}/globus ${globus_flavor}
-	ccflags="${ccflags} -I${egee_path}/globus/include/${globus_flavor} -I${egee_path}/lcg/include -I${egee_path}/edg/include  -I${egee_path}/lcg/include/lfc -I${egee_path}/lcg/include/dpm -DHAS_EGEE -DHAS_GLOBUS_GSS"
-	ldflags="${ldflags} -L${egee_path}/globus/lib -L${egee_path}/edg/lib -L${egee_path}/lcg/lib -ldpm -llfc -lgfal -llcg_util -lcgsi_plugin_gsoap_2.6 -lglobus_gss_assist_${globus_flavor} -lglobus_gssapi_gsi_${globus_flavor} -lglobus_gsi_proxy_core_${globus_flavor} -lglobus_gsi_credential_${globus_flavor} -lglobus_gsi_callback_${globus_flavor} -lglobus_oldgaa_${globus_flavor} -lglobus_gsi_sysconfig_${globus_flavor} -lglobus_gsi_cert_utils_${globus_flavor} -lglobus_openssl_${globus_flavor} -lglobus_proxy_ssl_${globus_flavor} -lglobus_openssl_error_${globus_flavor} -lglobus_common_${globus_flavor} -lldap_${globus_flavor} -llber_${globus_flavor} -lsasl -lssl_${globus_flavor} -lcrypto_${globus_flavor} -lltdl_${globus_flavor} -llutil_${globus_flavor} -luuid"
+	ccflags="${ccflags} -I${rfio_path}/include -DHAS_RFIO"
 else
-	has_egee=no
-	if [ $config_egee_path = yes ]
+	if [ $config_rfio_path = yes ]
 	then
-		echo "*** Sorry, I couldn't find EGEE in $egee_path"
-		echo "*** Check --with-egee-path and try again."
-		exit 1
+		  echo "*** Sorry, I couldn't find RFIO in $rfio_path"
+		  echo "*** Check --with-rfio-path and try again."
+		  exit 1
 	else
-		echo "*** skipping egee support"
-	fi
-fi
-
-if [ $has_egee = yes ]
-then
-	echo "using egee version of rfio"
-else
-	if [ $config_rfio_path != no ] && library_search shift ${rfio_path}
-	then
-		ccflags="${ccflags} -I${rfio_path}/include -DHAS_RFIO"
-	else
-		if [ $config_rfio_path = yes ]
-		then
-			  echo "*** Sorry, I couldn't find RFIO in $rfio_path"
-			  echo "*** Check --with-rfio-path and try again."
-			  exit 1
-		else
-			  echo "*** skipping rfio support"
-		fi
+		  echo "*** skipping rfio support"
 	fi
 fi
 
@@ -410,59 +413,54 @@ else
 	fi
 fi
 
-if [ $has_egee = yes ]
-then	
-	echo "using egee version of globus"
-else
-	if [ x$globus_flavor = xauto ]
+if [ x$globus_flavor = xauto ]
+then
+	if [ $build_cpu = X86_64 ] 
 	then
-		if [ $build_cpu = X86_64 ] 
-		then
-			globus_flavor=gcc64
-		else
-			globus_flavor=gcc32
-		fi
-	fi
-
-	echo "using a globus flavor of '$globus_flavor' (if this is wrong, use the --globus-flavor argument)"
-
-	if [ $config_globus_path != no ]
-	then
-		if check_file ${globus_path}/include/${globus_flavor}/globus_common.h
-		then
-			ccflags="${ccflags} -I${globus_path}/include/${globus_flavor} -DHAS_GLOBUS_GSS"
-			ldflags="${ldflags} -L${globus_path}/lib"
-			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
-			do
-				library_search ${library}_${globus_flavor} ${globus_path}
-			done
-
-			cctools_dynamic_auth_libs="${cctools_dynamic_auth_libs} -L${globus_path}/lib -lglobus_gss_assist_${globus_flavor}"
-
-		elif check_file ${globus_path}/include/globus/globus_common.h
-		then
-			ccflags="${ccflags} -I${globus_path}/lib/globus/include -I${globus_path}/include/globus -DHAS_GLOBUS_GSS"
-			ldflags="${ldflags} -L${globus_path}/lib"
-			for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
-			do
-				library_search $library ${globus_path}
-			done
-
-                        cctools_dynamic_auth_libs="${cctools_dynamic_auth_libs} -L${globus_path}/lib -lglobus_gss_assist"
-
-		else
-			if [ $config_globus_path = yes ]
-			then
-				echo "*** Sorry, I couldn't find Globus in $globus_path"
-				echo "*** Check --with-globus-path and try again."
-				exit 1
-			else
-				echo "*** skipping globus support"
-			fi
-		fi
+		globus_flavor=gcc64
 	else
-		echo "*** skipping globus support"
+		globus_flavor=gcc32
 	fi
+fi
+
+echo "using a globus flavor of '$globus_flavor' (if this is wrong, use the --globus-flavor argument)"
+
+if [ $config_globus_path != no ]
+then
+	if check_file ${globus_path}/include/${globus_flavor}/globus_common.h
+	then
+		ccflags="${ccflags} -I${globus_path}/include/${globus_flavor} -DHAS_GLOBUS_GSS"
+		ldflags="${ldflags} -L${globus_path}/lib"
+		for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
+		do
+			library_search ${library}_${globus_flavor} ${globus_path}
+		done
+
+		cctools_dynamic_auth_libs="${cctools_dynamic_auth_libs} -L${globus_path}/lib -lglobus_gss_assist_${globus_flavor}"
+
+	elif check_file ${globus_path}/include/globus/globus_common.h
+	then
+		ccflags="${ccflags} -I${globus_path}/lib/globus/include -I${globus_path}/include/globus -DHAS_GLOBUS_GSS"
+		ldflags="${ldflags} -L${globus_path}/lib"
+		for library in globus_gss_assist globus_gssapi_gsi globus_gsi_proxy_core globus_gsi_credential globus_gsi_callback globus_oldgaa globus_gsi_sysconfig globus_gsi_cert_utils globus_openssl globus_openssl_error globus_callout globus_proxy_ssl globus_common ltdl
+		do
+			library_search $library ${globus_path}
+		done
+
+		cctools_dynamic_auth_libs="${cctools_dynamic_auth_libs} -L${globus_path}/lib -lglobus_gss_assist"
+
+	else
+		if [ $config_globus_path = yes ]
+		then
+			echo "*** Sorry, I couldn't find Globus in $globus_path"
+			echo "*** Check --with-globus-path and try again."
+			exit 1
+		else
+			echo "*** skipping globus support"
+		fi
+	fi
+else
+	echo "*** skipping globus support"
 fi
 
 if [ $config_irods_path != no ] && library_search RodsAPIs "${irods_path}" core/obj
@@ -530,43 +528,6 @@ else
 	fi
 fi
 
-if [ $config_swig_path != no ]
-then
-	swig=""
-	if check_file ${swig_path}/bin/swig
-	then
-		swig=${swig_path}/bin/swig
-	else
-		if check_path swig
-		then
-			swig=`which swig`
-		else
-			echo "*** skipping swig bindings for work queue"
-		fi
-	fi
-
-	if [ -n "$swig" ]
-	then
-		swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
-		if [ `format_version $swig_version` -ge `format_version 1.3.40` ]
-		then
-			packages="${packages} ${include_package_work_queue}"
-		else
-			echo "*** Sorry, I need swig >= 1.3.40"
-			echo "*** skipping swig bindings for work queue"
-		fi
-	fi
-else
-	if [ $config_swig_path = yes ]
-	then
-		echo "*** Sorry, I couldn't find swig in $swig_path"
-		echo "*** Check --with=swig-path and try again."
-		exit 1
-	else
-		echo "*** skipping swig bindings for work queue"
-	fi
-fi
-
 if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
 then
 	if [ x$xrootd_arch = xauto ]
@@ -603,15 +564,13 @@ else
 	fi
 fi
 
-if [ $config_cvmfs_path != no ] && check_file ${cvmfs_path}/cvmfs/src/libcvmfs.h
+if [ $config_cvmfs_path != no ] && check_file ${cvmfs_path}/include/libcvmfs.h
 then
-	ccflags="${ccflags} -I${cvmfs_path}/cvmfs/src -DHAS_CVMFS"
+	ccflags="${ccflags} -I${cvmfs_path}/include -DHAS_CVMFS"
 
-	for library in cvmfs/src/cvmfs sqlite3/src/sqlite3 libcurl/src/lib/.libs/curl c-ares/src/.libs/cares
+	for library in cvmfs 
 	do
-		lib_path=${cvmfs_path}/`dirname ${library}`
-                library=`basename ${library}`
-		if ! library_search $library ${lib_path}
+		if ! library_search $library ${cvmfs_path}
 		then
 			echo "*** Couldn't find $library in ${lib_path}"
 			exit 1
@@ -650,8 +609,11 @@ then
 
 	if [ $build_sys = LINUX ]
 	then
+		# Remove the -lreadline that was added by "library_search readline" above
+		ldflags=`echo $ldflags | sed "s/-lreadline//"`
+
+		# Put the readline flags in a separate variable to be used only where needed.
 		cctools_readline_ldflags="-lreadline ${link_no_as_needed} -lncurses -lhistory ${link_as_needed}"
-		ldflags=`echo $ldflags | sed "s/-lreadline/$cctools_readline_ldflags/"`
 	else 
 		library_search ncurses ${readline_path}
 		library_search termcap ${readline_path}
@@ -726,10 +688,10 @@ then
 
 	if [ $perl != 0 ]
 	then
-		perl_version=`perl -e 'printf "%vd\n",$^V;'`
+		perl_version=`${perl} -e 'printf "%vd\n",$^V;'`
 		echo "perl version is ${perl_version}"
-		perl_ccflags=`perl -MExtUtils::Embed -e ccopts`
-		perl_ldflags=`perl -MExtUtils::Embed -e ldopts`
+		perl_ccflags=`${perl} -MExtUtils::Embed -e ccopts`
+		perl_ldflags=`${perl} -MExtUtils::Embed -e ldopts`
 		work_queue_bindings="$work_queue_bindings perl"
 	else
                 if [ $config_perl_path = yes ]
@@ -772,7 +734,7 @@ then
 				python_ccflags_file=`mktemp tmp.XXXXXX`
 				python_ldflags_file=`mktemp tmp.XXXXXX`
 
-				${python} > $python_ccflags_file <<EOF
+				env HOME=/var/empty ${python} > $python_ccflags_file <<EOF
 from distutils import sysconfig
 flags = ['-I' + sysconfig.get_python_inc(),
 	 '-I' + sysconfig.get_python_inc(plat_specific=True)]
@@ -781,7 +743,7 @@ if not syscfgflags is None:
     flags.extend(syscfgflags.split())
 print ' '.join(flags)
 EOF
-				${python} > $python_ldflags_file <<EOF
+				env HOME=/var/empty ${python} > $python_ldflags_file <<EOF
 from distutils import sysconfig
 libs = sysconfig.get_config_var('LIBS').split() + sysconfig.get_config_var('SYSLIBS').split()
 if not sysconfig.get_config_var('Py_ENABLE_SHARED'):
@@ -821,6 +783,48 @@ EOF
                 fi
 	fi
 fi
+
+if [ $config_swig_path != no ]
+then
+	swig=""
+	if check_file ${swig_path}/bin/swig
+	then
+		swig=${swig_path}/bin/swig
+	else
+		if check_path swig
+		then
+			swig=`which swig`
+		else
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+
+	if [ -n "$swig" ]
+	then
+		swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
+		if [ "$python" != 1 -a ! \( "$python_major_version" -eq 2 -a "$python_minor_version" -eq 4 \) -a `format_version $swig_version` -eq `format_version 1.3.29` ]
+		then
+			echo "*** Sorry, Swig 1.3.29 does not work with Python $python_version."
+			echo "*** skipping swig bindings for work queue"
+		elif [ `format_version $swig_version` -ge `format_version 1.3.29` ]
+		then
+			packages="${packages} ${include_package_work_queue}"
+		else
+			echo "*** Sorry, I need swig >= 1.3.29"
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+else
+	if [ $config_swig_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find swig in $swig_path"
+		echo "*** Check --with=swig-path and try again."
+		exit 1
+	else
+		echo "*** skipping swig bindings for work queue"
+	fi
+fi
+
 
 linker="gcc"
 
@@ -864,8 +868,10 @@ optional_function strsignal /usr/include/string.h HAS_STRSIGNAL
 optional_function pread /usr/include/unistd.h HAS_PREAD
 optional_function pwrite /usr/include/unistd.h HAS_PWRITE
 
-optional_include /usr/include/sys/statfs.h HAS_SYS_STATFS_H
-optional_include /usr/include/sys/statvfs.h HAS_SYS_STATVFS_H
+optional_include sys/statfs.h HAS_SYS_STATFS_H
+optional_include sys/statvfs.h HAS_SYS_STATVFS_H
+optional_include sys/xattr.h HAS_SYS_XATTR_H
+optional_include attr/xattr.h HAS_ATTR_XATTR_H
 
 cctools_doctargets=
 
@@ -900,12 +906,13 @@ else
 	debug_flag="-g"
 fi
 
-ccflags="${ccflags} -DINSTALL_PATH=\\\"${install_path}\\\" $debug_flag -D_REENTRANT -D_GNU_SOURCE -DBUILD_USER=\\\"$build_user\\\" -DBUILD_HOST=\\\"$build_host\\\" -DCCTOOLS_VERSION_MAJOR=$major -DCCTOOLS_VERSION_MINOR=$minor -DCCTOOLS_VERSION_MICRO=$micro -DCCTOOLS_OPSYS_${build_sys} -DCCTOOLS_CPU_${build_cpu}"
+ccflags="${ccflags} -DINSTALL_PATH='\"${install_path}\"' $debug_flag -D_REENTRANT -D_GNU_SOURCE -DBUILD_USER='\"$build_user\"' -DBUILD_HOST='\"$build_host\"' -DCCTOOLS_VERSION_MAJOR=$major -DCCTOOLS_VERSION_MINOR=$minor -DCCTOOLS_VERSION_MICRO=$micro -DCCTOOLS_VERSION='\"$version\"' -DCCTOOLS_RELEASE_DATE='\"$release_date\"' -DCCTOOLS_CONFIGURE_ARGUMENTS='\"$configure_arguments\"' -DCCTOOLS_SYSTEM_INFORMATION='\"$system_information\"' -DCCTOOLS_OPSYS_${build_sys} -DCCTOOLS_CPU_${build_cpu}"
+ldflags="${ldflags} ${debug_flag}"
 
 echo "Creating Makefile.config..."
 
 cat <<EOF >>Makefile.config
-# Generated at `date` by `whoami`@`uname -n`
+# Generated at `date` by $USER@`uname -n`
 
 CCTOOLS_INSTALL_DIR=${install_path}
 CCTOOLS_PACKAGES=${packages}
@@ -967,7 +974,7 @@ EOF
 echo ""
 echo "To re-configure, type './configure.rerun'"
 echo "To build, type '${MAKE}'"
-echo "To install, type '${MAKE} install'"
+echo "To build and install, type '${MAKE} install'"
 echo ""
 
 exit 0
