Updated to cctools r1815

diff --git a/cctools/configure b/cctools/configure
--- a/cctools/configure
+++ b/cctools/configure
@@ -8,8 +8,8 @@ save_arguments $0 $@
 
 major=3
 minor=4
-micro=0
-release_date="10/19/2011"
+micro=2
+release_date="02/10/2012"
 
 build_user=`whoami`
 build_host=`uname -n`
@@ -75,6 +75,7 @@ xrootd_path="/usr"
 cvmfs_path="/usr"
 mpi_path="/usr/local"
 zlib_path="/usr"
+swig_path="/usr"
 
 xrootd_arch=auto
 globus_flavor=auto
@@ -107,6 +108,7 @@ config_irods_path=no
 config_xrootd_path=no
 config_cvmfs_path=no
 config_mpi_path=no
+config_swig_path=auto
 
 if [ "X${GLOBUS_LOCATION}" != "X" ]
 then
@@ -205,6 +207,11 @@ do
 			mpi_path=$1
 			config_mpi_path=yes
 			;;
+		--with-swig-path)
+			shift
+			swig_path=$1
+			config_swig_path=yes
+			;;
 		--without-system-sand)
 			include_package_sand=""
 			if [ $include_package_allpairs != "" ]
@@ -269,6 +276,7 @@ Where PACKAGE may be:
     xrootd
     zlib
     cvmfs
+    swig
 
 And SYSTEM may be:
     sand
@@ -480,6 +488,21 @@ then
 	fi
 
 	ccflags="${ccflags} -DHAS_MYSQL -DHAS_BXGRID"
+
+	# MySQL requires zlib
+	if library_search z ${zlib_path}
+	then
+		if [ X${zlib_path} != X/usr ]
+		then
+		    
+			ccflags="${ccflags} -I${zlib_path}/include"
+			ldflags="${ldflags} -L${zlib_path}/lib"
+		fi
+	else
+		echo "*** Sorry, I couldn't find zlib in $zlib_path"
+		echo "*** Check --with-zlib-path and try again."
+		exit 1
+	fi
 else
 	if [ $config_mysql_path = yes ]
 	then
@@ -497,15 +520,52 @@ then
         usempi="true"
         ccflags="${ccflags} -I${mpi_path}/include -DHAS_MPI"
 else
-    usempi="false"
-    if [ $config_mpi_path = yes ]
-    then
-        echo "*** Sorry, I couldn't find mpicc or mpi.h in $mpi_path"
-        echo "*** Check --with-mpi-path and try again."
-        exit 1
-    else
-        echo "*** skipping mpi support"
-    fi
+	usempi="false"
+	if [ $config_mpi_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find mpicc or mpi.h in $mpi_path"
+		echo "*** Check --with-mpi-path and try again."
+		exit 1
+	else
+		echo "*** skipping mpi support"
+	fi
+fi
+
+if [ $config_swig_path != no ]
+then
+	swig=""
+	if check_file ${swig_path}/bin/swig
+	then
+		swig=${swig_path}/bin/swig
+	else
+		if check_path swig
+		then
+			swig=`which swig`
+		else
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+
+	if [ -n "$swig" ]
+	then
+		swig_version=`${swig} -version | grep -i version | awk '{print $3}'`
+		if [ `format_version $swig_version` -ge `format_version 1.3.40` ]
+		then
+			packages="${packages} ${include_package_work_queue}"
+		else
+			echo "*** Sorry, I need swig >= 1.3.40"
+			echo "*** skipping swig bindings for work queue"
+		fi
+	fi
+else
+	if [ $config_swig_path = yes ]
+	then
+		echo "*** Sorry, I couldn't find swig in $swig_path"
+		echo "*** Check --with=swig-path and try again."
+		exit 1
+	else
+		echo "*** skipping swig bindings for work queue"
+	fi
 fi
 
 if [ $config_xrootd_path != no ] && check_file ${xrootd_path}/include/xrootd/XrdVersion.hh
@@ -591,7 +651,7 @@ then
 
 	if [ $build_sys = LINUX ]
 	then
-		cctools_readline_ldflags="-lreadline ${link_no_as_needed} -lncurses -ltermcap -lhistory ${link_as_needed}"
+		cctools_readline_ldflags="-lreadline ${link_no_as_needed} -lncurses -lhistory ${link_as_needed}"
 	else 
 		library_search ncurses ${readline_path}
 		library_search termcap ${readline_path}
@@ -625,19 +685,6 @@ else
 	echo "*** skipping fuse support"
 fi
 
-if library_search z ${zlib_path}
-then
-	if [ X${zlib_path} != X/usr ]
-	then
-		ccflags="${ccflags} -I${zlib_path}/include"
-		ldflags="${ldflags} -L${zlib_path}/lib"
-	fi
-else
-	echo "*** Sorry, I couldn't find zlib in $zlib_path"
-	echo "*** Check --with-zlib-path and try again."
-	exit 1
-fi
-
 # Solaris places kerberos includes in a strange place.
 
 if [ -d ${krb5_path}/include/kerberosv5 ]
@@ -666,13 +713,6 @@ else
 	else
 		echo "*** skipping krb5 support"
 	fi
-fi
-
-if check_path swig
-then
-	packages="${packages} ${include_package_work_queue}"
-else
-	echo "*** skipping swig bindings for work queue"
 fi
 
 if [ $config_perl_path != no ]
@@ -724,7 +764,7 @@ then
 		echo "python version is ${python_version}"
 		python_major_version=`echo ${python_version} | cut -d . -f 1`
 		python_minor_version=`echo ${python_version} | cut -d . -f 2`
-		if [ $python_major_version -eq 2 -a $python_minor_version -ge 4 ]
+		if [ "$python_major_version" -eq 2 -a "$python_minor_version" -ge 4 ]
 		then
 			if check_file ${python_path}/include/python2.$python_minor_version/Python.h
 			then
@@ -890,6 +930,8 @@ CXXFLAGS=\$(CCTOOLS_CXXFLAGS)
 MPILD=\$(CCTOOLS_MPI_LD)
 
 CCTOOLS_AR=ar
+
+CCTOOLS_SWIG=${swig}
 
 CCTOOLS_PERL=${perl}
 CCTOOLS_PERL_CCFLAGS=${perl_ccflags}
